@startuml
enum GeneroPelicula {
  ACCION
  COMEDIA
  DRAMA
  TERROR
  DOCUMENTAL
}
GeneroPelicula <-- Pelicula
class Pelicula {
  - id: int
  - titulo: String
  - genero: GeneroPelicula
  - duracion: int
  - anioLanzamiento: int
  - sinopsis: String
  - calificacion: double
  + Pelicula(id: int, titulo: GeneroPelicula, genero: GeneroPelicula, duracion: int, anioLanzamiento: int, sinopsis: String,
             calificacion: double)
}

class Usuario {
  - idUsuario: int
  - perfiles: List<Perfil>
  - dispositivos: List<Dispositivo>
  + Usuario(idUsuario: int)
  + crearPerfil(nombre: String): Perfil
  + eliminarPerfil(perfilId: int): void
  + agregarDispositivo(dispositivo: Dispositivo): void
  + calcularCosto(): float
  - cantidadReproducciones(): int
}

class Perfil {
  - id: int
  - nombre: String
  - favoritos: List<Pelicula>
  - historial: List<Reproduccion>

  + Perfil(id: int, nombre: String)
  + agregarAFavorito(pelicula: Pelicula): void
  + verHistorial(): List<Reproduccion>
  + iniciarReproduccion(pelicula: Pelicula, dispositivo: Dispositivo): Reproduccion
  - contarReproducciones(): int
}

class Dispositivo {
  - ip: String
  - nombre: String
  + Dispositivo(ip: String, nombre: String)
}

class Reproduccion {
  - fechaHora: DateTime
  - pelicula: Pelicula
  - dispositivo: Dispositivo
  -perfil:Perfil
  + Reproduccion(pelicula: Pelicula, dispositivo: Dispositivo, fechaHora: DateTime, perfil: Perfil)
}

Usuario "1" o-- "0..*" Perfil
Usuario "1" o-- "0..*" Dispositivo
Perfil "1" o-- "0..*" Pelicula
Perfil "1" o-- "1" Reproduccion
Reproduccion "1" --o "1" Pelicula
Reproduccion "1" --o "1" Dispositivo

class PlataformaStreaming {
  - usuarios: List<Usuario>
  - peliculas: List<Pelicula>
  - dispositivos: List<Dispositivo>
  + Sistema()
  + agregarUsuario(idUsuario: int): Usuario
  + agregarPelicula(pelicula: Pelicula): void
  + agregarDispositivo(dispositivo: Dispositivo): void
  + calcularCostoUsuario(idUsuario: int): float
  - buscarUsuario(id: int): Usuario
  - buscarPelicula(id: int): Pelicula
  - buscarDispositivo(ip: String): Dispositivo
}

PlataformaStreaming "1" *-- "0..*" Usuario
PlataformaStreaming "1" *-- "0..*" Pelicula
PlataformaStreaming "1" *-- "0..*" Dispositivo


@enduml
