@startuml
actor Usuario
participant PlataformaStreaming as PS
participant UsuarioObjeto       as U
participant Perfil           as P

Usuario -> PS : calcularCosto(idUsuario)
activate PS

alt usuario existe
  PS -> PS : buscarUsuario(idUsuario)
  PS --> PS : usuario       ' devolución interna

  PS -> U : calcularCosto()
  activate U

  U -> U : cantidadPerfiles()
  U --> U : nPerfiles

  U -> U : cantidadDispositivos()
  U --> U : nDispositivos

  U -> U : getPerfiles() : List<Perfil>
  U --> U : listaPerfiles
  loop por cada perfil in listaPerfiles
    U -> P : cantidadReproducciones()
    activate P
    P --> U : repro_i
    deactivate P
  end
  U --> U : totalReproducciones

  U -> U : calcularCosto(nPerfiles, nDispositivos, totalReproducciones)
  U --> PS : costo : float
  deactivate U

  PS --> Usuario : costo : float
else usuario no existe
  PS --> Usuario : exceptionMessage("Usuario no encontrado")
end

@enduml