@startuml
actor "Usuario"
participant "SistemaSubte"
participant "LineaSubte"
participant "VagonArgentino"

"Usuario" ->"SistemaSubte": agregarVagonArgentino(String nombreLinea):void
activate "SistemaSubte"

"SistemaSubte" -> "VagonArgentino": VagonArgentino(String nombre):VagonArgentino
activate "VagonArgentino"
"VagonArgentino"->"VagonArgentino":super(25)
"VagonArgentino"-->"SistemaSubte": VagonArgentino vagonArgentino
deactivate "VagonArgentino"

"SistemaSubte" -> "SistemaSubte":agregarVagonLinea(VagonArgentino vagonArgentino):void
activate "SistemaSubte"

"SistemaSubte"-> "SistemaSubte": buscarLinea(String nombreLinea):LineaSubte
activate "SistemaSubte"
loop por cada linea
"SistemaSubte"->"LineaSubte": sosLinea(String nombreLinea):boolean
"LineaSubte" --> "SistemaSubte": boolean
end
"SistemaSubte"-->"SistemaSubte": lineaSubte

deactivate "SistemaSubte"
"SistemaSubte"->"LineaSubte": agregarVagon(VagonArgentino vagonArgentino):void
activate "LineaSubte"
"LineaSubte"->"LineaSubte":esCompatibleConVagones(vagon):boolean
"LineaSubte"->"LineaSubte":superaMaximoEstacion(vagon):boolean

deactivate "VagonArgentino"
alt esCompatibleConVagones=true && superaMaximoEstacion=false
"LineaSubte"->"LineaSubte": vagones.add(VagonArgentino vagonArgentino)
else

"LineaSubte"-->"SistemaSubte":ExceptionMessage("No se puede agregar el vagon dado que es incompatible")
"SistemaSubte"-->"Usuario": ExceptionMessage("No se puede agregar el vagon dado que es incompatible")
end
@enduml